config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # Tournaments routes
  get   "/tournaments/new",        to: "tournaments#new"
  post  "/tournaments/new",        to: "tournaments#create"
  get   "/tournaments",            to: "tournaments#index"
  get   "/tournaments/:id"         =>  "tournaments#show", as: "tournament"
  patch "/tournaments/:id/open"    =>  "tournaments#open_registration",
         as: "tournaments_open"
  patch "/tournaments/:id/close"   =>  "tournaments#close_registration",
         as: "tournaments_close"
  get   "/tournaments/:id/checkin" =>  "tournaments#checkin",
         as: "tournaments_checkin"
  get   "/tournaments/:id/manage"  =>  "tournaments#manage",
         as: "tournaments_manage"
  get   "/tournaments/:id/edit"    =>  "tournaments#edit",
         as: "tournaments_edit"
  patch "/tournaments/:id/edit"    =>  "tournaments#update",
         as: "tournaments_update"
  get   "/tournaments/:id/csv"     =>  "tournaments#generate_csv",
         as: "tournaments_csv"
  get   "/tournaments/:id/checkin/filter" => "tournaments#filter_checkin",
         as: "tournaments_checkin_filter"
  get   "/tournaments/:id/attendees"      => "tournaments#show_attendees",
         as: "tournaments_attendees_show"
  get   "/tournaments/:id/attendees/filter" => "tournaments#filter_attendees",
         as: "tournaments_attendees_filter"

  # AboutText routes
  get   "/texts",              to: "about_texts#index"
  get   "/texts/:section/edit" =>  "about_texts#edit",   as: "text_edit"
  patch "/texts/:section/edit" =>  "about_texts#update", as: "text_update"

  # Attendees routes
  get  "/tournaments/:id/register"                          => "attendees#new",
        as: "attendees_new"
  post "/tournaments/:id/register"                          => "attendees#create",
        as: "attendees_create"
  get   "/tournaments/:id/register/confirmation"            => "attendees#confirm",
         as: "attendees_confirmation"
  get  "/tournaments/:id/attendees/:attendee_id"            => "attendees#show",
        as: "attendee"
  patch "/tournaments/:id/attendees/:attendee_id/checkin"   => "attendees#checkin",
         as: "attendees_checkin"
  patch "/tournaments/:id/attendees/:attendee_id/uncheckin" => "attendees#uncheckin",
         as: "attendees_uncheckin"
  patch "/tournaments/:id/attendees/:attendee_id/paid"      => "attendees#paid",
         as: "attendees_paid"
  patch "/tournaments/:id/attendees/:attendee_id/unpaid"    => "attendees#unpaid",
         as: "attendees_unpaid"

  # Images routes
  get   "/images",         to: "images#index"
  get   "/images/:id/edit" =>  "images#edit",   as: "images_edit"
  patch "/images/:id/edit" =>  "images#update", as: "images_update"

  # Links routes
  get   "/donate",             to: "links#donate"
  get   "/40for40",            to: "links#donate"
  get   "/dues/non-traveling", to: "links#dues_regular"
  get   "/dues/traveling",     to: "links#dues_traveling"
  get   "/volunteer",          to: "links#volunteer"
  get   "/join",               to: "links#join"
  get   "/links",              to: "links#index"
  get   "/links/:name/edit"    =>  "links#edit", as: "link_edit"
  patch "/links/:name/edit"    =>  "links#update", as: "link_update"

  # PracticeTimes routes
  get    "/practices",     to: "practice_times#index"
  get    "/practices/new", to: "practice_times#new"
  post   "/practices/new", to: "practice_times#create"
  delete "/practices/:id"  =>  "practice_times#destroy", as: "practices_delete"

  # Representatives routes
  get    "/representatives/new",     to: "representatives#new"
  post   "/representatives/new",     to: "representatives#create"
  get    "/representatives",         to: "representatives#index"
  delete "/representatives/:id"      =>  "representatives#destroy",
          as: "representatives_delete"
  get    "/representatives/:id/edit" =>  "representatives#edit",
          as: "representatives_edit"
  patch  "/representatives/:id/edit" =>  "representatives#update",
          as: "representatives_update"

  # Sessions routes
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # StaticPages routes
  get "/dues", to: "static_pages#dues"

  # Testing routes
  get   "/testing",                to: "testings#testing"
  get   "/testing/sheets/edit",    to: "testings#index"
  get   "/testing/sheets/:id/edit" =>  "testings#edit", as: "testing_edit"
  patch "/testing/sheets/:id/edit" =>  "testings#update", as: "testing_update"

  # Transaction routes
  get  "/transactions",        to: "transactions#home"
  get  "/transactions/update", to: "transactions#update"
  post "/transactions/scrape", to: "transactions#scrape"
  get  "/charts/revenue",      to: "transactions#revenue_charts"
  get  "/charts/spending",     to: "transactions#spending_charts"
  get  "/charts/comparison",   to: "transactions#comparison_charts"

  # Users routes
  get    "/manage",                  to: "users#manage"
  get    "/profile/password/change", to: "users#edit_password"
  patch  "/profile/password/change", to: "users#update_password"
  get    "/profile/password/set",    to: "users#set_password"
  patch  "/profile/password/set",    to: "users#create_password"
  get    "/users/new",               to: "users#new"
  post   "/users/new",               to: "users#create"
  get    "/users",                   to: "users#index"
  delete "/users/:id"                =>  "users#destroy", as: "users_delete"

  # Resources
  resources :account_activations, only: [:edit]
end

app/models/representative.rb
require 'carrierwave/orm/activerecord'

class Representative < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  PRESIDENT = 0
  VP = 1
  REP = 2

  POSITIONS = {
    PRESIDENT => "President",
    VP => "Vice President",
    REP => "Representative"
  }

  # Causing tests to fail
  if !Rails.env.test?
    mount_uploader :photo, RepresentativePhotoUploader
    validate(:check_dimensions, on: :create)
  end

  validates(:name,     presence: true)
  validates(:email,    presence: true,
                       length: {maximum: 255},
                       format: {with: VALID_EMAIL_REGEX},
                       uniqueness: {case_sensitive: false})
  validates(:position, presence: true)
  validates(:photo,    presence: true)
  validate(:position_available)

  ##
  # Gets the name of the position of this representative
  def position_name
    POSITIONS[self.position]
  end

  ##
  # Gets the select options for representative positions
  def Representative.position_select
    result = []
    POSITIONS.each do |id, position|
      result << [position, id]
    end

    result
  end

  private

  ##
  # Validates the dimensions of the uploaded photo
  def check_dimensions
    if !photo_cache.nil? && (photo.width != 640 || photo.height != 480)
      errors.add(:photo, "must be 640x480 pixels")
    end
  end

  ##
  # Validates that a representative can be added to this position
  #
  # Fails if the position is for the President or Vice-President and a
  # Representative for that position already exists and is not this
  # Representative
  def position_available
    if position != REP
      rep = Representative.find_by(position: position)
      if !rep.nil? && rep != self
        errors.add(:position, "has already been filled")
      end
    end
  end
end

app/controllers/representatives_controller.rb
class RepresentativesController < ApplicationController

  before_action :logged_in_user

  ##
  # Form for a user to create a new representative
  # GET /representatives/new
  def new
    @rep = Representative.new
  end

  ##
  # Creates the new representative
  # POST /representatives/new
  def create
    @rep = Representative.new(create_params)
    if @rep.save
      flash[:success] = "Created #{@rep.name}"
      redirect_to(representatives_path)
    else
      if !Rails.env.test?
        @rep.remove_photo!
      end
      render("new")
    end
  end

  ##
  # Deletes a representative
  # DELETE /representatives/:id
  def destroy
    rep = Representative.find_by(id: params[:id])
    if !rep.nil?
      name = rep.name
      rep.destroy
      flash[:success] = "Deleted #{name}."
    end

    redirect_to(representatives_path)
  end

  ##
  # Page to edit a representative's information
  # GET /representatives/:id/edit
  def edit
    @rep = Representative.find_by(id: params[:id])
  end

  ##
  # Updates a representative's information
  # PATCH /representatives/:id/edit
  def update
    @rep = Representative.find_by(id: params[:id])
    if @rep.update_attributes(update_params)
      flash[:success] = "Successfully updated #{@rep.name}"
      redirect_to(representatives_path)
    else
      render("edit")
    end
  end

  ##
  # Gets all the representatives
  # GET /representatives
  def index
    @reps = Representative.order(position: :asc, name: :asc)
  end

  private

  ##
  # Parameters for creating a representative
  def create_params
    params.require(:representative).permit(:name, :email, :position, :photo)
  end
 
  ##
  # Parameters for updating a representative
  def update_params
    params.require(:representative).permit(:name, :email, :position)
  end

end

app/views/representatives/_index_card.html.erb
<div class="rep-index-card text-index-card shadow">
    <div class="row">
        <div class="col-xs-12 col-sm-8">
            <h3><b><%= rep.name %></b><br></h3>

            <div class="large-text">
                <b>Position:</b> <%= rep.position_name %><br>
                <b>Email:</b> <%= rep.email %><br>

                <%= render("representatives/index_links",
                           rep: rep,
                           css: "large-screen") %>
            </div>
        </div>

        <div class="col-xs-12 col-sm-4">
            <% if !Rails.env.test? %>
                <%= image_tag(rep.photo.url, class: "img-fluid") %>
            <% end %>
        </div>
    </div>

    <%= render("representatives/index_links",
               rep: rep,
               css: "small-screen large-text") %>
</div>
<div class="move-down"></div>

app/views/representatives/_index_links.html.erb
<div class="move-down <%= css %>">
    <%= link_to(representatives_edit_path(id: rep.id)) do %>
        <%= fa_icon("edit") %> edit
    <% end %>
    &nbsp;
    <%= link_to(representatives_delete_path(id: rep.id),
                method: :delete,
                data: {confirm: "Are you sure you wish to delete #{rep.name}?"},
                class: "red") do %>
        <%= fa_icon("trash") %> delete
    <% end %>
</div>

app/views/representatives/edit.html.erb
<% provide(:title, "Edit #{@rep.name}") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-8 large-text">
        <%= form_for(@rep, url: representatives_update_path,
                     method: :patch) do |f| %>
            <%= render("shared/error_messages", obj: @rep) %>

            <%= f.label(:name) %>
            <%= f.text_field(:name, class: "form-control") %>

            <%= f.label(:email) %>
            <%= f.email_field(:email, class: "form-control") %>

            <%= f.label(:position) %>
            <%= f.select(:position,
                         options_for_select(Representative.position_select, @rep.position),
                         {},
                         class: "form-control") %>

            <%= f.submit("Update", class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>

app/views/representatives/index.html.erb
<% provide(:title, "Representatives") %>

<%= render("shared/manage_header") %>

<div class="container">
    <div class="row justify-content-around index-content">
        <div class="col-xs-12 col-sm-10 col-md-8">
            <%= link_to("New Representative", representatives_new_path,
                        class: "btn btn-primary btn-full") %>

            <% @reps.each do |rep| %>
                <%= render("representatives/index_card", rep: rep) %>
            <% end %>
        </div>
    </div>
</div>

app/views/representatives/new.html.erb
<% provide(:title, "New Representative") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-8 large-text">
        <%= form_for(@rep, url: representatives_new_path,
                     method: :post) do |f| %>
            <%= render("shared/error_messages", obj: @rep) %>

            <%= f.label(:name) %>
            <%= f.text_field(:name, class: "form-control") %>

            <%= f.label(:email) %>
            <%= f.email_field(:email, class: "form-control") %>

            <%= f.label(:position) %>
            <%= f.select(:position,
                         options_for_select(Representative.position_select),
                         {},
                         class: "form-control") %>

            <%= f.label(:photo, "Photo (640x480 px)") %>
            <%= f.file_field(:photo, class: "form-control") %>

            <%= f.submit("Create Representative",
                         class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>