config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # Tournaments routes
  get   "/tournaments/new",        to: "tournaments#new"
  post  "/tournaments/new",        to: "tournaments#create"
  get   "/tournaments",            to: "tournaments#index"
  get   "/tournaments/:id"         =>  "tournaments#show", as: "tournament"
  patch "/tournaments/:id/open"    =>  "tournaments#open_registration",
         as: "tournaments_open"
  patch "/tournaments/:id/close"   =>  "tournaments#close_registration",
         as: "tournaments_close"
  get   "/tournaments/:id/checkin" =>  "tournaments#checkin",
         as: "tournaments_checkin"
  get   "/tournaments/:id/manage"  =>  "tournaments#manage",
         as: "tournaments_manage"
  get   "/tournaments/:id/edit"    =>  "tournaments#edit",
         as: "tournaments_edit"
  patch "/tournaments/:id/edit"    =>  "tournaments#update",
         as: "tournaments_update"
  get   "/tournaments/:id/csv"     =>  "tournaments#generate_csv",
         as: "tournaments_csv"
  get   "/tournaments/:id/checkin/filter" => "tournaments#filter_checkin",
         as: "tournaments_checkin_filter"
  get   "/tournaments/:id/attendees"      => "tournaments#show_attendees",
         as: "tournaments_attendees_show"
  get   "/tournaments/:id/attendees/filter" => "tournaments#filter_attendees",
         as: "tournaments_attendees_filter"

  # AboutText routes
  get   "/texts",              to: "about_texts#index"
  get   "/texts/:section/edit" =>  "about_texts#edit",   as: "text_edit"
  patch "/texts/:section/edit" =>  "about_texts#update", as: "text_update"

  # Attendees routes
  get  "/tournaments/:id/register"                          => "attendees#new",
        as: "attendees_new"
  post "/tournaments/:id/register"                          => "attendees#create",
        as: "attendees_create"
  get   "/tournaments/:id/register/confirmation"            => "attendees#confirm",
         as: "attendees_confirmation"
  get  "/tournaments/:id/attendees/:attendee_id"            => "attendees#show",
        as: "attendee"
  patch "/tournaments/:id/attendees/:attendee_id/checkin"   => "attendees#checkin",
         as: "attendees_checkin"
  patch "/tournaments/:id/attendees/:attendee_id/uncheckin" => "attendees#uncheckin",
         as: "attendees_uncheckin"
  patch "/tournaments/:id/attendees/:attendee_id/paid"      => "attendees#paid",
         as: "attendees_paid"
  patch "/tournaments/:id/attendees/:attendee_id/unpaid"    => "attendees#unpaid",
         as: "attendees_unpaid"

  # Images routes
  get   "/images",         to: "images#index"
  get   "/images/:id/edit" =>  "images#edit",   as: "images_edit"
  patch "/images/:id/edit" =>  "images#update", as: "images_update"

  # Links routes
  get   "/donate",             to: "links#donate"
  get   "/40for40",            to: "links#donate"
  get   "/dues/non-traveling", to: "links#dues_regular"
  get   "/dues/traveling",     to: "links#dues_traveling"
  get   "/volunteer",          to: "links#volunteer"
  get   "/join",               to: "links#join"
  get   "/links",              to: "links#index"
  get   "/links/:name/edit"    =>  "links#edit", as: "link_edit"
  patch "/links/:name/edit"    =>  "links#update", as: "link_update"

  # PracticeTimes routes
  get    "/practices",     to: "practice_times#index"
  get    "/practices/new", to: "practice_times#new"
  post   "/practices/new", to: "practice_times#create"
  delete "/practices/:id"  =>  "practice_times#destroy", as: "practices_delete"

  # Representatives routes
  get    "/representatives/new",     to: "representatives#new"
  post   "/representatives/new",     to: "representatives#create"
  get    "/representatives",         to: "representatives#index"
  delete "/representatives/:id"      =>  "representatives#destroy",
          as: "representatives_delete"
  get    "/representatives/:id/edit" =>  "representatives#edit",
          as: "representatives_edit"
  patch  "/representatives/:id/edit" =>  "representatives#update",
          as: "representatives_update"

  # Sessions routes
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # StaticPages routes
  get "/dues", to: "static_pages#dues"

  # Testing routes
  get   "/testing",                to: "testings#testing"
  get   "/testing/sheets/edit",    to: "testings#index"
  get   "/testing/sheets/:id/edit" =>  "testings#edit", as: "testing_edit"
  patch "/testing/sheets/:id/edit" =>  "testings#update", as: "testing_update"

  # Transaction routes
  get  "/transactions",        to: "transactions#home"
  get  "/transactions/update", to: "transactions#update"
  post "/transactions/scrape", to: "transactions#scrape"
  get  "/charts/revenue",      to: "transactions#revenue_charts"
  get  "/charts/spending",     to: "transactions#spending_charts"
  get  "/charts/comparison",   to: "transactions#comparison_charts"

  # Users routes
  get    "/manage",                  to: "users#manage"
  get    "/profile/password/change", to: "users#edit_password"
  patch  "/profile/password/change", to: "users#update_password"
  get    "/profile/password/set",    to: "users#set_password"
  patch  "/profile/password/set",    to: "users#create_password"
  get    "/users/new",               to: "users#new"
  post   "/users/new",               to: "users#create"
  get    "/users",                   to: "users#index"
  delete "/users/:id"                =>  "users#destroy", as: "users_delete"

  # Resources
  resources :account_activations, only: [:edit]
end

app/models/user.rb
class User < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  attr_accessor :activation_token

  has_secure_password

  before_save :downcase_email

  validates(:email,    presence: true,
                       length: {maximum: 255},
                       format: {with: VALID_EMAIL_REGEX},
                       uniqueness: {case_sensitive: false})
  validates(:password, presence: true,
                       length: {minimum: 8},
                       allow_nil: true)

  ##
  # Authenticates the given token
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    if digest.nil?
      return false
    else
      BCrypt::Password.new(digest).is_password?(token)
    end
  end

  ##
  # Returns true if the email is valid, false otherwise
  def valid_email?
    self.valid?
    self.errors.delete(:password)
    self.errors[:email].blank?
  end

  ##
  # Sends the activation email for this user
  def send_activation_email
    if !self.activated?
      self.activation_token = User.new_token
      self.update_attribute(:activation_digest,
                            User.digest(self.activation_token))
      UserMailer.account_activation(self).deliver_now
    end
  end

  ##
  # Activates this user's account
  def activate
    if !self.activated?
      self.update_attribute(:activated, true)
      self.update_attribute(:activated_at, DateTime.now)
    end
  end

  ##
  # Creates a digest from the given string using BCrypt
  # string:   the string to digest
  # Returns the digest
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  ##
  # Generates a new url safe token
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  private

  ##
  # Converts the user's email to all lowercase
  def downcase_email
    self.email = email.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user
  before_action :valid_user,        only:   [:destroy]
  before_action :no_password,       only:   [:set_password, :create_password]

  skip_before_action :has_password, only: [:set_password, :create_password]

  ##
  # Form to create a new user from
  # GET /users/new
  def new
    @user = User.new
  end

  ##
  # Creates a new user
  # POST /users/new
  def create
    @user = User.new(create_params)
    if @user.valid_email?
      @user.save(validate: false)
      @user.send_activation_email
      flash[:success] = "Created user #{@user.email}"
      redirect_to(users_path)
    else
      render("new")
    end
  end

  ##
  # Page to display all users
  # GET /users
  def index
    @users = User.order(email: :asc)
  end

  ##
  # Page for users to manage the site
  # GET /manage
  def manage
  end

  ##
  # Deletes a user
  # DELETE /users/:id
  def destroy
    user = User.find(params[:id])
    user.delete
    flash[:success] = "Deleted user"
    redirect_to(users_path)
  end

  ##
  # Form for a new user to set their password
  # GET /profile/password/set
  def set_password
    @user = current_user
  end

  ##
  # Sets the user's password
  # PATCH /profile/password/set
  def create_password
    @user = current_user
    if @user.update_attributes(create_password_params)
      flash[:success] = "Successfully created your account"
      redirect_to(root_url)
    else
      render("set_password")
    end
  end

  ##
  # Form for user to change password
  # GET /profile/password/change
  def edit_password
    @user = current_user
  end

  ##
  # Changes the user's password
  # PATCH /profile/password/change
  def update_password
    @user  = current_user

    params = update_password_params
    if @user.authenticated?("password", params[:old_password])
      if params[:new_password].empty?
        @user.errors.add(:new_password, "cannot be empty.")
        render("edit_password")
      elsif @user.authenticated?("password", params[:new_password])
        @user.errors.add(:new_password, "cannot match old password.")
        render("edit_password")
      elsif @user.update_attributes({
          password: params[:new_password],
          password_confirmation: params[:password_confirmation]})
        flash[:success] = "Updated password"
        redirect_to(root_url)
      else
        render("edit_password")
      end
    else
      @user.errors.add(:old_password, "was incorrect.")
      render("edit_password")
    end
  end
  
  private

  ##
  # Parameters for creating a user
  def create_params
    params.require(:user).permit(:email)
  end

  ##
  # Parameters for creating a user's password
  def create_password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

  ##
  # Parameters for updating a password
  def update_password_params
    params.require(:user).permit(:old_password, :new_password,
                                 :password_confirmation)
  end

  ##
  # Redirect if given an invalid user
  def valid_user
    user = User.find_by(id: params[:id])
    if user.nil?
      flash[:danger] = "Could not find that user"
      redirect_to(users_path)
    end
  end

  ##
  # Redirect user if they have already set a password
  def no_password
    user = current_user
    if !user.password_digest.nil?
      redirect_to(profile_password_change_path)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper

  ##
  # Formats the given time to US Central Time
  #
  # time:   the DateTime to format
  #
  # Returns the formatted time string
  def format_time(time)
    time = time.in_time_zone("Central Time (US & Canada)")
    time.strftime("%b %d, %Y %H:%M %Z")
  end
end

app/views/users/_index_card.html.erb
<div class="text-index-card shadow">
    <h3><b><%= user.email %></b></h3>
    <div>
        <b>Account status:</b>
        <% if user.activated? %>
            <span class="green">Activated</span>
            <br>
            <b>Activated at:</b> <%= format_time(user.activated_at) %>
        <% else %>
            <span class="red">Not Activated</span>
            <br>
            <b>Created at:</b> <%= format_time(user.created_at) %>
        <% end %>
    </div>

    <div class="move-down">
        <%= link_to(users_delete_path(id: user.id),
                    method: :delete,
                    data: {
                        confirm: "Are you sure you wish to " +
                                 "delete #{user.email}?"
                    },
                    class: "red") do %>
            <%= fa_icon("trash") %> delete user
        <% end %>
    </div>
</div>
<div class="move-down"></div>

app/views/users/edit_password.html.erb
<% provide(:title, "Change Password") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-8">
        <%= form_for(@user, url: profile_password_change_path,
                     method: :patch) do |f| %>
            <%= render("shared/error_messages", obj: @user) %>

            <%= f.label(:old_password, "Old Password") %>
            <%= f.password_field(:old_password, class: "form-control") %>

            <%= f.label(:new_password, "New Password") %>
            <%= f.password_field(:new_password, class: "form-control") %>

            <%= f.label(:password_confirmation, "Confirm Password") %>
            <%= f.password_field(:password_confirmation,
                class: "form-control") %>

            <%= f.submit("Change Password",
                         class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users") %>

<%= render("shared/manage_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-10 col-md-8 large-text">
        <%= link_to("New User", users_new_path,
                    class: "btn btn-primary btn-full") %>

        <% @users.each do |user| %>
            <%= render("users/index_card", user: user) %>
        <% end %>
    </div>
</div>

app/views/users/manage.html.erb
<% provide(:title, "Manage") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-10 col-md-8">
        <h3>Transactions</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(transactions_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("money") %> Transactions
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(charts_comparison_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("area-chart") %> Charts
                <% end %>
            </div>
        </div>

        <h3 class="move-down">Users</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(users_path, class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("address-book-o") %> Users
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(users_new_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("plus") %> New User
                <% end %>
            </div>
        </div>

        <h3 class="move-down">Representatives</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(representatives_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("group") %> Representatives
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(representatives_new_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("plus") %> New Representative
                <% end %>
            </div>
        </div>

        <h3 class="move-down">Tournaments</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(tournaments_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("trophy") %> Tournaments
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(tournaments_new_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("plus") %> New Tournament
                <% end %>
            </div>
        </div>

        <h3 class="move-down">Practice Times</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(practices_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("calendar-o") %> Practice Times
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(practices_new_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("plus") %> New Practice Time
                <% end %>
            </div>
        </div>

        <h3 class="move-down">Site Content</h3>
        <div class="row">
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(testing_sheets_edit_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("file-o") %> Testing Sheets
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(images_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("file-image-o") %> Site Images
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(texts_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("file-text-o") %> Site Text
                <% end %>
            </div>
            <div class="col-xs-12 col-sm-6 move-down">
                <%= link_to(links_path,
                            class: "btn btn-primary btn-full") do %>
                    <%= fa_icon("link") %> Site Links
                <% end %>
            </div>
        </div>
        <div class="move-down"></div>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "New User") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-8 large-text">
        <%= form_for(@user, url: users_new_path) do |f| %>
            <%= render("shared/error_messages", obj: @user) %>

            <%= f.label(:email) %>
            <%= f.email_field(:email, class: "form-control") %>

            <%= f.submit("Create User", class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>

app/views/users/set_password.html.erb
<% provide(:title, "Set Password") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-10 col-md-8 large-text">
        <%= form_for(@user, url: profile_password_set_path) do |f| %>
            <%= render("shared/error_messages", obj: @user) %>

            <%= f.label(:password) %>
            <%= f.password_field(:password, class: "form-control") %>

            <%= f.label(:password_confirmation) %>
            <%= f.password_field(:password_confirmation,
                                 class: "form-control") %>

            <%= f.submit("Set Password", class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>