config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # Tournaments routes
  get   "/tournaments/new",        to: "tournaments#new"
  post  "/tournaments/new",        to: "tournaments#create"
  get   "/tournaments",            to: "tournaments#index"
  get   "/tournaments/:id"         =>  "tournaments#show", as: "tournament"
  patch "/tournaments/:id/open"    =>  "tournaments#open_registration",
         as: "tournaments_open"
  patch "/tournaments/:id/close"   =>  "tournaments#close_registration",
         as: "tournaments_close"
  get   "/tournaments/:id/checkin" =>  "tournaments#checkin",
         as: "tournaments_checkin"
  get   "/tournaments/:id/manage"  =>  "tournaments#manage",
         as: "tournaments_manage"
  get   "/tournaments/:id/edit"    =>  "tournaments#edit",
         as: "tournaments_edit"
  patch "/tournaments/:id/edit"    =>  "tournaments#update",
         as: "tournaments_update"
  get   "/tournaments/:id/csv"     =>  "tournaments#generate_csv",
         as: "tournaments_csv"
  get   "/tournaments/:id/checkin/filter" => "tournaments#filter_checkin",
         as: "tournaments_checkin_filter"
  get   "/tournaments/:id/attendees"      => "tournaments#show_attendees",
         as: "tournaments_attendees_show"
  get   "/tournaments/:id/attendees/filter" => "tournaments#filter_attendees",
         as: "tournaments_attendees_filter"

  # AboutText routes
  get   "/texts",              to: "about_texts#index"
  get   "/texts/:section/edit" =>  "about_texts#edit",   as: "text_edit"
  patch "/texts/:section/edit" =>  "about_texts#update", as: "text_update"

  # Attendees routes
  get  "/tournaments/:id/register"                          => "attendees#new",
        as: "attendees_new"
  post "/tournaments/:id/register"                          => "attendees#create",
        as: "attendees_create"
  get   "/tournaments/:id/register/confirmation"            => "attendees#confirm",
         as: "attendees_confirmation"
  get  "/tournaments/:id/attendees/:attendee_id"            => "attendees#show",
        as: "attendee"
  patch "/tournaments/:id/attendees/:attendee_id/checkin"   => "attendees#checkin",
         as: "attendees_checkin"
  patch "/tournaments/:id/attendees/:attendee_id/uncheckin" => "attendees#uncheckin",
         as: "attendees_uncheckin"
  patch "/tournaments/:id/attendees/:attendee_id/paid"      => "attendees#paid",
         as: "attendees_paid"
  patch "/tournaments/:id/attendees/:attendee_id/unpaid"    => "attendees#unpaid",
         as: "attendees_unpaid"

  # Images routes
  get   "/images",         to: "images#index"
  get   "/images/:id/edit" =>  "images#edit",   as: "images_edit"
  patch "/images/:id/edit" =>  "images#update", as: "images_update"

  # Links routes
  get   "/donate",             to: "links#donate"
  get   "/40for40",            to: "links#donate"
  get   "/dues/non-traveling", to: "links#dues_regular"
  get   "/dues/traveling",     to: "links#dues_traveling"
  get   "/volunteer",          to: "links#volunteer"
  get   "/join",               to: "links#join"
  get   "/links",              to: "links#index"
  get   "/links/:name/edit"    =>  "links#edit", as: "link_edit"
  patch "/links/:name/edit"    =>  "links#update", as: "link_update"

  # PracticeTimes routes
  get    "/practices",     to: "practice_times#index"
  get    "/practices/new", to: "practice_times#new"
  post   "/practices/new", to: "practice_times#create"
  delete "/practices/:id"  =>  "practice_times#destroy", as: "practices_delete"

  # Representatives routes
  get    "/representatives/new",     to: "representatives#new"
  post   "/representatives/new",     to: "representatives#create"
  get    "/representatives",         to: "representatives#index"
  delete "/representatives/:id"      =>  "representatives#destroy",
          as: "representatives_delete"
  get    "/representatives/:id/edit" =>  "representatives#edit",
          as: "representatives_edit"
  patch  "/representatives/:id/edit" =>  "representatives#update",
          as: "representatives_update"

  # Sessions routes
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # StaticPages routes
  get "/dues", to: "static_pages#dues"

  # Testing routes
  get   "/testing",                to: "testings#testing"
  get   "/testing/sheets/edit",    to: "testings#index"
  get   "/testing/sheets/:id/edit" =>  "testings#edit", as: "testing_edit"
  patch "/testing/sheets/:id/edit" =>  "testings#update", as: "testing_update"

  # Transaction routes
  get  "/transactions",        to: "transactions#home"
  get  "/transactions/update", to: "transactions#update"
  post "/transactions/scrape", to: "transactions#scrape"
  get  "/charts/revenue",      to: "transactions#revenue_charts"
  get  "/charts/spending",     to: "transactions#spending_charts"
  get  "/charts/comparison",   to: "transactions#comparison_charts"

  # Users routes
  get    "/manage",                  to: "users#manage"
  get    "/profile/password/change", to: "users#edit_password"
  patch  "/profile/password/change", to: "users#update_password"
  get    "/profile/password/set",    to: "users#set_password"
  patch  "/profile/password/set",    to: "users#create_password"
  get    "/users/new",               to: "users#new"
  post   "/users/new",               to: "users#create"
  get    "/users",                   to: "users#index"
  delete "/users/:id"                =>  "users#destroy", as: "users_delete"

  # Resources
  resources :account_activations, only: [:edit]
end

app/models/attendee.rb
class Attendee < ApplicationRecord

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  # Ranks an attendee can be
  RANKS = {
    0  => "White Belt",
    1  => "Yellow Stripe",
    2  => "Yellow Belt",
    3  => "Green Stripe",
    4  => "Green Belt",
    5  => "Blue Stripe",
    6  => "Blue Belt",
    7  => "Red Stripe",
    8  => "Red Belt",
    9  => "Black Stripe",
    10 => "1st Dan",
    11 => "2nd Dan",
    12 => "3rd Dan",
    13 => "4th Dan",
    14 => "5th Dan",
    15 => "6th Dan",
    16 => "7th Dan",
    17 => "8th Dan",
    18 => "9th Dan",
  }

  # Weight classes for black belts
  WEIGHT_CLASSES = {
    0 => "Micro Weight (-110, -99,-125.7, -110)",
    1 => "Light Weight (110-123.5, 99-110, 125.7-139, 110-123.5)",
    2 => "Middle Weight (123.5-136.7, 110-121, 139-154.3, 123.5-136.7)",
    3 => "Light Heavy Weight (136.7-150, 121-132.3, 154.3-172, 136.7-150)",
    4 => "Heavy Weight (150-165.4, 132.3-143.3, 172-187.4, 150-165.4)",
    5 => "Hyper Weight (+165.4, +143.3, +187.4, +165.4)"
  }

  # Names of each weight class
  WEIGHT_CLASS_NAMES = {
    0 => "Micro Weight",
    1 => "Light Weight",
    2 => "Middle Weight",
    3 => "Light Heavy Weight",
    4 => "Heavy Weight",
    5 => "Hyper Weight"
  }

  # Sex options
  SEXES = {
    0 => "Male",
    1 => "Female"
  }

  belongs_to :tournament

  validates(:first_name,      presence: true)
  validates(:last_name,       presence: true)
  validates(:rank,            presence: true)
  validates(:school,          presence: true)
  validates(:instructor,      presence: true)
  validates(:age,             presence: true,
                              numericality: {greater_than: 0})
  validates(:weight_class,    presence: true)
  validates(:sex,             presence: true)
  validates(:street,          presence: true)
  validates(:city,            presence: true)
  validates(:state,           presence: true)
  validates(:zip,             presence: true)
  validates(:phone,           presence: true)
  validates(:email,           presence: true,
                              length: {maximum: 255},
                              format: {with: VALID_EMAIL_REGEX})
  validates(:accepted_waiver, inclusion: {in: [true],
                                          message: "must be accepted"})

  ##
  # Gets the name of the rank of this attendee
  def rank_name
    RANKS[self.rank]
  end
 
  ##
  # Gets the name of the weight class of this attendee
  def weight_class_name
    WEIGHT_CLASS_NAMES[self.weight_class]
  end

  ##
  # Gets the name of the sex of this attendee
  def sex_name
    SEXES[self.sex]
  end

  ##
  # Gets the names of the events this attendee has signed up for
  def event_names
    events = []
    if self.patterns?
      events << "patterns"
    end

    if self.sparring?
      events << "sparring"
    end

    if self.breaking?
      events << "breaking"
    end

    if self.team_demo?
      events << "team demo"
    end

    events.join(", ")
  end

  ##
  # Send the confirmation email to this attendee
  def send_confirmation_email
    AttendeeMailer.registration_confirmation(self).deliver_now
  end

  ##
  # Adds this attendee to the given csv
  #
  # csv:  the csv to add to
  def to_csv(csv)
    result = []
    result << self.first_name
    result << self.last_name
    result << self.rank_name
    result << self.school
    result << self.instructor
    result << self.age
    result << self.weight_class_name
    result << self.sex_name
    result << self.patterns
    result << self.sparring
    result << self.breaking
    result << self.team_demo
    result << self.team_demo_name

    csv << result
  end

  def weak_match?(term)
    self.first_name.downcase.include?(term) ||
      self.last_name.downcase.include?(term)
  end

  def strong_match?(term)
    "#{self.first_name.downcase} #{self.last_name.downcase}".include?(term) ||
      "#{self.last_name.downcase} #{self.first_name.downcase}".include?(term)
  end

  ##
  # Gets the rank options for select
  #
  # include_none:   whether or not to include a "None" option. (default false)
  def Attendee.rank_select(include_none=false)
    Attendee.hash_to_select(RANKS, include_none)
  end

  ##
  # Gets the weight class options for select
  #
  # include_none:   whether or not to include a "None" option. (default false)
  def Attendee.weight_class_select(include_none=false)
    Attendee.hash_to_select(WEIGHT_CLASSES, include_none)
  end
 
  ##
  # Gets the weight class options for select
  #
  # include_none:   whether or not to include a "None" option. (default false)
  def Attendee.weight_class_name_select(include_none=false)
    Attendee.hash_to_select(WEIGHT_CLASS_NAMES, include_none)
  end

  ##
  # Gets the sex options for select
  #
  # include_none:   whether or not to include a "None" option. (default false)
  def Attendee.sex_select(include_none=false)
    Attendee.hash_to_select(SEXES, include_none)
  end

  ##
  # Gets the event options for select
  #
  # include_none:   whether or not to include a "None" option. (default false)
  def Attendee.events_select(include_none=false)
    result = [
      ["Patterns", "patterns"],
      ["Sparring", "sparring"],
      ["Board Breaking", "breaking"],
      ["Team Demo", "team_demo"]
    ]
    if include_none
      result = [["None", ""]] + result
    end

    result
  end

  private

  ##
  # Converts the given hash into an array for select where the value of the hash
  # is the value displayed in the select and the key of the hash is the actual
  # value of the select
  #
  # include_none:   whether or not to include a "None" option.
  def Attendee.hash_to_select(h, include_none)
    result = []
    if include_none
      result << ["None", ""]
    end

    h.each do |k, v|
      result << [v, k]
    end

    result
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  before_action :logged_in_user,    only: [:show, :checkin, :uncheckin, :paid,
                                           :unpaid]
  before_action :valid_tournament
  before_action :valid_attendee,    only: [:show, :checkin, :uncheckin, :paid,
                                           :unpaid]
  before_action :registration_open, only: [:new, :create]

  ##
  # Form to register for a tournament
  # GET /tournaments/:id/register
  def new
    @tournament = Tournament.get(params[:id])
    @attendee = Attendee.new
  end

  ##
  # Register the user for the tournament
  # POST /tournaments/:id/register
  def create
    @tournament = Tournament.get(params[:id])
    @attendee = Attendee.new(create_params)

    if verify_recaptcha(model: @attendee) && @attendee.save
      @attendee.send_confirmation_email
      redirect_to(attendees_confirmation_path)
    else
      render("new")
    end
  end

  ##
  # Show confirmation to user after registering
  # GET /tournaments/:id/register/confirmation
  def confirm
    @tournament = Tournament.get(params[:id])
  end

  ##
  # Shows information for a single attendee
  # GET /tournaments/:id/attendees/:attendee_id
  def show
    @tournament = Tournament.get(params[:id])
    @attendee = Attendee.find(params[:attendee_id])
  end

  ##
  # Checks in an attendee
  # PATCH /tournaments/:id/attendees/:attendee_id/checkin
  def checkin
    tournament = Tournament.get(params[:id])
    attendee = Attendee.find(params[:attendee_id])
    if !attendee.update_attribute(:checked_in, true)
      flash[:danger] = "Failed to check in #{attendee.first_name} " +
                       "#{attendee.last_name}"
    end

    redirect_to(tournaments_checkin_path(id: tournament.path,
                                         query: params[:query]))
  end

  ##
  # Removes check in from an attendee
  # PATCH /tournaments/:id/attendees/:attendee_id/uncheckin
  def uncheckin
    tournament = Tournament.get(params[:id])
    attendee = Attendee.find(params[:attendee_id])
    if !attendee.update_attribute(:checked_in, false)
      flash[:danger] = "Failed to remove check in from " +
                       "#{attendee.first_name} #{attendee.last_name}"
    end

    redirect_to(tournaments_checkin_path(id: tournament.path,
                                         query: params[:query]))
  end

  ##
  # Marks an attendee as having had paid their entry fee
  # PATCH /tournaments/:id/attendees/paid
  def paid
    tournament = Tournament.get(params[:id])
    attendee = Attendee.find(params[:attendee_id])
    if !attendee.update_attribute(:paid, true)
      flash[:danger] = "Failed to mark #{attendee.first_name} " +
                      "#{attendee.last_name} as paid."
    end

    redirect_to(tournaments_checkin_path(id: tournament.path,
                                         query: params[:query]))
  end

  ##
  # Removes mark as paid from an attendee
  # PATCH /tournaments/:id/attendees/unpaid
  def unpaid
    tournament = Tournament.get(params[:id])
    attendee = Attendee.find(params[:attendee_id])
    if !attendee.update_attribute(:paid, false)
      flash[:danger] = "Failed to remove mark as paid from " +
                       "#{attendee.first_name} #{attendee.last_name}"
    end

    redirect_to(tournaments_checkin_path(id: tournament.path,
                                         query: params[:query]))
  end

  private

  ##
  # Parameters to create an attendee
  def create_params
    params.require(:attendee).permit(:first_name, :last_name, :rank, :school,
                                     :instructor, :patterns, :sparring,
                                     :breaking, :age, :weight_class, :sex,
                                     :street, :city, :zip, :phone, :email,
                                     :team_demo, :team_demo_name,
                                     :accepted_waiver, :tournament_id, :state)
  end

  ##
  # Redirect user if registration is not open for the tournament
  def registration_open
    tournament = Tournament.get(params[:id])
    if !tournament.registration_open?
      flash[:danger] = "Registration is not open yet for #{tournament.name}"
      redirect_to(tournaments_path)
    end
  end

  ##
  # Redirect user if given invalid attendee ID
  def valid_attendee
    tournament = Tournament.get(params[:id])
    attendee = Attendee.find_by(id: params[:attendee_id])
    if attendee.nil?
      flash[:danger] = "Failed to find that attendee"
      redirect_to(tournament_path(id: tournament.path))
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper

  ##
  # Gets the select options for states
  def state_select
    [
      "Alabama",
      "Alaska",
      "Arizona",
      "Arkansas",
      "California",
      "Colorado",
      "Connecticut",
      "Delaware",
      "Florida",
      "Georgia",
      "Hawaii",
      "Idaho",
      "Illinois",
      "Indiana",
      "Iowa",
      "Kansas",
      "Kentucky",
      "Louisiana",
      "Maine",
      "Maryland",
      "Massachusetts",
      "Michigan",
      "Minnesota",
      "Mississippi",
      "Missouri",
      "Montana",
      "Nebraska",
      "Nevada",
      "New Hampshire",
      "New Jersey",
      "New Mexico",
      "New York",
      "North Carolina",
      "North Dakota",
      "Ohio",
      "Oklahoma",
      "Oregon",
      "Pennsylvania",
      "Rhode Island",
      "South Carolina",
      "South Dakota",
      "Tennessee",
      "Texas",
      "Utah",
      "Vermont",
      "Virginia",
      "Washington",
      "West Virginia",
      "Wisconsin",
      "Wyoming",
    ]
  end

end

app/views/attendees/_form_contact.html.erb
<div class="attendee-form-section">
    <h3><%= fa_icon("address-card-o") %>&nbsp; Contact information</h3>
    <%= f.label(:street) %>
    <%= f.text_field(:street, placeholder: "* Required",
                     class: "form-control " +
                            "#{validation_class(@attendee, "street")}"
                    ) %>
    <%= render("shared/validation_message", obj: @attendee, field: "street") %>

    <%= f.label(:city) %>
    <%= f.text_field(:city, placeholder: "* Required",
                     class: "form-control " +
                            "#{validation_class(@attendee, "city")}"
                    ) %>
    <%= render("shared/validation_message", obj: @attendee, field: "city") %>

    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <%= f.label(:state) %>
            <%= f.select(:state, options_for_select(state_select),
                         {},
                     class: "form-control " +
                            "#{validation_class(@attendee, "state")}"
                    ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "state") %>
        </div>

        <div class="col-xs-12 col-sm-6">
            <%= f.label(:zip) %>
            <%= f.text_field(:zip, placeholder: "* Required",
                     class: "form-control " +
                            "#{validation_class(@attendee, "zip")}"
                    ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "zip") %>
        </div>
    </div>

    <%= f.label(:email) %>
    <%= f.email_field(:email, placeholder: "* Required",
                      class: "form-control " +
                             "#{validation_class(@attendee, "email")}"
                     ) %>
    <% if @attendee.errors.include?("email") %>
        <div class="validation-message">
            Must be a valid email
        </div>
    <% end %>

    <%= f.label(:phone) %>
    <%= f.text_field(:phone, placeholder: "* Required",
                     class: "form-control " +
                            "#{validation_class(@attendee, "phone")}"
                    ) %>
    <%= render("shared/validation_message", obj: @attendee, field: "phone") %>
</div>

app/views/attendees/_form_events.html.erb
<div class="attendee-form-section">
    <h3><%= fa_icon("flag-checkered") %>&nbsp; Events</h3>

    <label class="checkbox-container">Patterns
        <%= f.check_box(:patterns) %>
        <span class="checkmark"></span>
    </label>

    <label class="checkbox-container">Sparring
        <%= f.check_box(:sparring) %>
        <span class="checkmark"></span>
    </label>

    <label class="checkbox-container">Board breaking
        <%= f.check_box(:breaking) %>
        <span class="checkmark"></span>
    </label>

    <label class="checkbox-container">Team demonstration
        <%= f.check_box(:team_demo) %>
        <span class="checkmark"></span>
    </label>

    <%= f.label(:team_demo_name, "Demo team name") %>
    <%= f.text_field(:team_demo_name, class: "form-control") %>
</div>

app/views/attendees/_form_information.html.erb
<div class="attendee-form-section">
    <h3><%= fa_icon("info-circle") %>&nbsp; Information</h3>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <%= f.label(:first_name) %>
            <%= f.text_field(:first_name, placeholder: "* Required",
                             class: "form-control " +
                                    "#{validation_class(@attendee, "first_name")}"
                            ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "first_name") %>
        </div>

        <div class="col-xs-12 col-sm-6">
            <%= f.label(:last_name) %>
            <%= f.text_field(:last_name, placeholder: "* Required",
                             class: "form-control " +
                                    "#{validation_class(@attendee, "last_name")}"
                            ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "last_name") %>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <%= f.label(:age) %>
            <%= f.number_field(:age, min: 1, placeholder: "* Required",
                               class: "form-control " +
                                      "#{validation_class(@attendee, "age")}"
                              ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "age") %>
        </div>

        <div class="col-xs-12 col-sm-6">
            <%= f.label(:sex) %>
            <%= f.select(:sex, options_for_select(Attendee.sex_select),
                         {},
                         class: "form-control " +
                                "#{validation_class(@attendee, "sex")}"
                        ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "sex") %>
        </div>
    </div>

    <%= f.label(:rank) %>
    <%= f.select(:rank, options_for_select(Attendee.rank_select),
                 {},
                 class: "form-control " +
                        "#{validation_class(@attendee, "rank")}"
                ) %>
    <%= render("shared/validation_message", obj: @attendee,
                                            field: "rank") %>

    <%= f.label(:weight_class,
                "Weight Class (Jun. M., Jun. F., Sen. M., Sen. F. " +
                "[5 lbs. leeway])") %>
    <%= f.select(:weight_class, options_for_select(Attendee.weight_class_select),
                 {},
                 class: "form-control " +
                        "#{validation_class(@attendee, "weight_class")}"
                ) %>
    <%= render("shared/validation_message", obj: @attendee,
                                            field: "weight_class") %>

    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <%= f.label(:instructor) %>
            <%= f.text_field(:instructor, placeholder: "* Required",
                             class: "form-control " +
                                    "#{validation_class(@attendee, "instructor")}"
                            ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "instructor") %>
        </div>

        <div class="col-xs-12 col-sm-6">
            <%= f.label(:school) %>
            <%= f.text_field(:school, placeholder: "* Required",
                             class: "form-control " +
                                    "#{validation_class(@attendee, "school")}"
                            ) %>
            <%= render("shared/validation_message", obj: @attendee,
                                                    field: "school") %>
        </div>
    </div>
</div>

app/views/attendees/_form_waiver.html.erb
<div class="attendee-form-section">
    <h3 class="move-down"><%= fa_icon("file-o") %>&nbsp; Waiver</h3>

    <p>
        I understand that participating in this event can potentially lead to
        serious injury. By confirming below, I agree to release the University
        of Texas at Austin, the UT Recreational Sports Center, the UT ITF
        <nobr>Taekwon-Do</nobr> Club, all their employees, members, staff and
        any other tournament officials, sponsors, or hosts from all liability
        should I be injured by participating in this tournament. I also
        understand that registration is <b>not</b> complete until the $50
        competitor fee is paid.
    </p>

    <label class="checkbox-container">I Accept
        <%= f.check_box(:accepted_waiver) %>
        <span class="checkmark"></span>
    </label>
    <% if @attendee.errors.include?("accepted_waiver") %>
        <div class="validation-message small-move-down">
            You must accept the waiver
        </div>
    <% end %>
</div>

app/views/attendees/_show_contact.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 attendee-show-section large-text">
    <h3>Contact Information</h3>
    <div>
        Email:
        <span class="right"><%= @attendee.email %></span>
    </div>

    <div>
        Phone:
        <span class="right"><%= @attendee.phone %></span>
    </div>

    <div>
        Street:
        <span class="right"><%= @attendee.street %></span>
    </div>

    <div>
        City:
        <span class="right"><%= @attendee.city %></span>
    </div>

    <div>
        State:
        <span class="right"><%= @attendee.state %></span>
    </div>

    <div>
        Zip:
        <span class="right"><%= @attendee.zip %></span>
    </div>
</div>

app/views/attendees/_show_events.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 attendee-show-section large-text">
    <h3>Events</h3>
    <div>
        Patterns:
        <span class="right">
            <% if @attendee.patterns? %>
                <span class="green"><%= fa_icon("check") %></span>
            <% else %>
                <span class="red"><%= fa_icon("times") %></span>
            <% end %>
        </span>
    </div>

    <div>
        Sparring:
        <span class="right">
            <% if @attendee.sparring? %>
                <span class="green"><%= fa_icon("check") %></span>
            <% else %>
                <span class="red"><%= fa_icon("times") %></span>
            <% end %>
        </span>
    </div>

    <div>
        Breaking:
        <span class="right">
            <% if @attendee.breaking? %>
                <span class="green"><%= fa_icon("check") %></span>
            <% else %>
                <span class="red"><%= fa_icon("times") %></span>
            <% end %>
        </span>
    </div>

    <div>
        Team demo:
        <span class="right">
            <% if @attendee.team_demo? %>
                <span class="green"><%= fa_icon("check") %></span>
            <% else %>
                <span class="red"><%= fa_icon("times") %></span>
            <% end %>
        </span>
    </div>

    <% if @attendee.team_demo? %>
        <div>
            Demo team name:
            <span class="right"><%= @attendee.team_demo_name %></span>
        </div>
    <% end %>
</div>

app/views/attendees/confirm.html.erb
<% provide(:title, "Registration Submitted") %>

<%= render("shared/page_header") %>

<div class="row justify-content-around">
    <div class="col-xs-12 col-sm-10">
        <h2 class="center">
            You have been registered for the<br>
            <%= link_to(@tournament.name,
                        tournament_path(id: @tournament.path)) %>
            on
            <b><%= format_date(@tournament.event_date) %></b>
        </h2>

        <div class="large-text move-down">
            <p>
                Your registration is <b>not complete</b> until you have paid the
                <b>$50</b> entry fee. You may pay online
                <%= link_to("here",
                            @tournament.payment_link,
                            target: :_blank) %>
                or on the day of the tournament.
            </p>

            <p>
                If you are paying by check it <b class="underline">MUST</b> be
                made out to <b>UT Austin</b> with <b>UT ITF Taekwon-Do</b> in
                the memo line.
            </p>

            <div class="tournament-show-section">
                <h2><%= fa_icon("calendar") %> When</h2>
                <b><%= @tournament.event_date.strftime("%A, %B %d, %Y") %></b>
                <br>
                Doors open: <b><%= @tournament.checkin_time %></b><br>
                Event starts: <b><%= @tournament.start_time %></b>
            </div>

            <div class="tournament-show-section">
                <h2><%= fa_icon("map") %> Where</h2>
                UT Recreational Sports Center<br>
                2001 San Jacinto Blvd, Austin TX 78705

                <div class="maps-iframe">
                    <iframe src="https://www.google.com/maps/embed/v1/place?q=2001%20San%20Jacinto%20austin%20tx&key=AIzaSyDoVc_WfIhgv8z8tTg2hkHgIuZDWMd78tA"
                            frameborder="0"
                            style="border:0"
                            class="shadow"
                            allowfullscreen>
                    </iframe>
                </div>
            </div>

            <p>
                We look forward to seeing you in
                <%= @tournament.event_date.strftime("%B") %>!
            </p>

            <%= link_to(attendees_new_path(id: @tournament.path),
                        class: "btn btn-primary btn-full move-down") do %>
                <%= fa_icon("calendar-check-o") %>
                Register another Competitor
            <% end %>
            <div class="move-down"></div>
        </div>
    </div>
</div>