config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  # Tournaments routes
  get   "/tournaments/new",        to: "tournaments#new"
  post  "/tournaments/new",        to: "tournaments#create"
  get   "/tournaments",            to: "tournaments#index"
  get   "/tournaments/:id"         =>  "tournaments#show", as: "tournament"
  patch "/tournaments/:id/open"    =>  "tournaments#open_registration",
         as: "tournaments_open"
  patch "/tournaments/:id/close"   =>  "tournaments#close_registration",
         as: "tournaments_close"
  get   "/tournaments/:id/checkin" =>  "tournaments#checkin",
         as: "tournaments_checkin"
  get   "/tournaments/:id/manage"  =>  "tournaments#manage",
         as: "tournaments_manage"
  get   "/tournaments/:id/edit"    =>  "tournaments#edit",
         as: "tournaments_edit"
  patch "/tournaments/:id/edit"    =>  "tournaments#update",
         as: "tournaments_update"
  get   "/tournaments/:id/csv"     =>  "tournaments#generate_csv",
         as: "tournaments_csv"
  get   "/tournaments/:id/checkin/filter" => "tournaments#filter_checkin",
         as: "tournaments_checkin_filter"
  get   "/tournaments/:id/attendees"      => "tournaments#show_attendees",
         as: "tournaments_attendees_show"
  get   "/tournaments/:id/attendees/filter" => "tournaments#filter_attendees",
         as: "tournaments_attendees_filter"

  # AboutText routes
  get   "/texts",              to: "about_texts#index"
  get   "/texts/:section/edit" =>  "about_texts#edit",   as: "text_edit"
  patch "/texts/:section/edit" =>  "about_texts#update", as: "text_update"

  # Attendees routes
  get  "/tournaments/:id/register"                          => "attendees#new",
        as: "attendees_new"
  post "/tournaments/:id/register"                          => "attendees#create",
        as: "attendees_create"
  get   "/tournaments/:id/register/confirmation"            => "attendees#confirm",
         as: "attendees_confirmation"
  get  "/tournaments/:id/attendees/:attendee_id"            => "attendees#show",
        as: "attendee"
  patch "/tournaments/:id/attendees/:attendee_id/checkin"   => "attendees#checkin",
         as: "attendees_checkin"
  patch "/tournaments/:id/attendees/:attendee_id/uncheckin" => "attendees#uncheckin",
         as: "attendees_uncheckin"
  patch "/tournaments/:id/attendees/:attendee_id/paid"      => "attendees#paid",
         as: "attendees_paid"
  patch "/tournaments/:id/attendees/:attendee_id/unpaid"    => "attendees#unpaid",
         as: "attendees_unpaid"

  # Images routes
  get   "/images",         to: "images#index"
  get   "/images/:id/edit" =>  "images#edit",   as: "images_edit"
  patch "/images/:id/edit" =>  "images#update", as: "images_update"

  # Links routes
  get   "/donate",             to: "links#donate"
  get   "/40for40",            to: "links#donate"
  get   "/dues/non-traveling", to: "links#dues_regular"
  get   "/dues/traveling",     to: "links#dues_traveling"
  get   "/volunteer",          to: "links#volunteer"
  get   "/join",               to: "links#join"
  get   "/links",              to: "links#index"
  get   "/links/:name/edit"    =>  "links#edit", as: "link_edit"
  patch "/links/:name/edit"    =>  "links#update", as: "link_update"

  # PracticeTimes routes
  get    "/practices",     to: "practice_times#index"
  get    "/practices/new", to: "practice_times#new"
  post   "/practices/new", to: "practice_times#create"
  delete "/practices/:id"  =>  "practice_times#destroy", as: "practices_delete"

  # Representatives routes
  get    "/representatives/new",     to: "representatives#new"
  post   "/representatives/new",     to: "representatives#create"
  get    "/representatives",         to: "representatives#index"
  delete "/representatives/:id"      =>  "representatives#destroy",
          as: "representatives_delete"
  get    "/representatives/:id/edit" =>  "representatives#edit",
          as: "representatives_edit"
  patch  "/representatives/:id/edit" =>  "representatives#update",
          as: "representatives_update"

  # Sessions routes
  get    "/login",  to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  # StaticPages routes
  get "/dues", to: "static_pages#dues"

  # Testing routes
  get   "/testing",                to: "testings#testing"
  get   "/testing/sheets/edit",    to: "testings#index"
  get   "/testing/sheets/:id/edit" =>  "testings#edit", as: "testing_edit"
  patch "/testing/sheets/:id/edit" =>  "testings#update", as: "testing_update"

  # Transaction routes
  get  "/transactions",        to: "transactions#home"
  get  "/transactions/update", to: "transactions#update"
  post "/transactions/scrape", to: "transactions#scrape"
  get  "/charts/revenue",      to: "transactions#revenue_charts"
  get  "/charts/spending",     to: "transactions#spending_charts"
  get  "/charts/comparison",   to: "transactions#comparison_charts"

  # Users routes
  get    "/manage",                  to: "users#manage"
  get    "/profile/password/change", to: "users#edit_password"
  patch  "/profile/password/change", to: "users#update_password"
  get    "/profile/password/set",    to: "users#set_password"
  patch  "/profile/password/set",    to: "users#create_password"
  get    "/users/new",               to: "users#new"
  post   "/users/new",               to: "users#create"
  get    "/users",                   to: "users#index"
  delete "/users/:id"                =>  "users#destroy", as: "users_delete"

  # Resources
  resources :account_activations, only: [:edit]
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :logged_in_user

  ##
  # The main page for transactions
  # GET /transactions
  def home
    @studentorg = Transaction.where(account: "studentorg")
    @allocations = Transaction.where(account: "allocation")
    @donations = Transaction.where(account: "donation")
  end

  ##
  # Form for the user to update transactions
  # GET /transactions/update
  def update
  end

  ##
  # Reads the transactions from the given file
  # POST /transactions/scrape
  def scrape
    page = Nokogiri::HTML(File.read(scrape_params[:import_file].path))
    Transaction.build_all(page)
    redirect_to(transactions_path)
  end

  ##
  # Shows the visualization charts for revenue
  # GET /charts/revenue
  def revenue_charts
    @revenue_by_year = RevenueChartData.revenue_by_year
    @revenue_by_semester = RevenueChartData.revenue_by_semester
    @revenue_by_category = RevenueChartData.revenue_by_category
    @revenue_by_category_and_year = RevenueChartData.revenue_by_category_and_year
    @revenue_by_category_splits = RevenueChartData.revenue_by_category_splits
    @dues_by_year = RevenueChartData.dues_by_year
    @dues_by_semester = RevenueChartData.dues_by_semester
    @tournament_by_year = RevenueChartData.tournament_by_year
    @donations_by_year = RevenueChartData.donations_by_year
    @donations_by_semester = RevenueChartData.donations_by_semester
    @allocations_by_year = RevenueChartData.allocations_by_year
    @misc_by_year = RevenueChartData.misc_by_year
  end

  ##
  # Shows the visualization charts for spending
  # GET /charts/spending
  def spending_charts
    @spending_by_year = SpendingChartData.spending_by_year
    @spending_by_semester = SpendingChartData.spending_by_semester
    @spending_by_category = SpendingChartData.spending_by_category
    @spending_by_category_and_year = SpendingChartData.spending_by_category_and_year
    @spending_by_category_splits = SpendingChartData.spending_by_category_splits
  end

  ##
  # Shows the visualization charts for comparison between revenue and spending
  def comparison_charts
    @comparison_by_year = ComparisonChartData.comparison_by_year
    @comparison_by_year_negated = ComparisonChartData.comparison_by_year(true)
    @comparison_by_totals = ComparisonChartData.comparison_by_totals
  end

  private

  ##
  # The parameters for scraping transactions
  def scrape_params
    params.require(:update).permit(:import_file)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  ##
  # Calculates the number of revenue transactions
  #
  # transactions:   the transactions to count from
  #
  # Returns: the number of revenue transactions
  def revenue_count(transactions)
    transactions.where(spending: false).count
  end

  ##
  # Calculates the number of spending transactions
  #
  # transactions:   the transactions to count from
  #
  # Returns: the number of spending transactions
  def spending_count(transactions)
    transactions.where(spending: true).count
  end

  ##
  # Calculates the net amount
  #
  # transactions:   the transactions to calculate from
  #
  # Returns: the net amount
  def calc_net(transactions)
    calc_revenue(transactions) - calc_spending(transactions)
  end

  ##
  # Determines the net color
  #
  # transactions:   the transactions to determine from
  #
  # Returns: green if positive, red if negative, black if zero
  def net_color(transactions)
    net = calc_net(transactions)
    if net > 0 
      "green"
    elsif net < 0
      "red"
    else
      ""
    end
  end

  ##
  # Calculates the amount of revenue
  #
  # transactions:   the transactions to calculate from
  #
  # Returns: the amount of revenue
  def calc_revenue(transactions)
    sum = 0
    transactions.where(spending: false).each do |transaction|
      sum += transaction.amount.abs
    end

    sum
  end

  ##
  # Calculates the amount of spending
  #
  # transactions:   the transactions to calculate from
  #
  # Returns: the amount of spending
  def calc_spending(transactions)
    sum = 0
    transactions.where(spending: true).each do |transaction|
      sum += transaction.amount.abs
    end

    sum
  end
end

app/views/transactions/_area_chart.html.erb
<div id="<%= name %>-area" class="hidden">
    <%= area_chart(chart_data,
                   adapter: "highcharts",
                   prefix: "$",
                   colors: colors,
                   thousands: ",",
                   title: title,
                   curve: false,
                   stacked: stacked,
                   download: {background: "#FFFFFF",
                              filename: name},
                   library: {
                       plotOptions: {
                            animation: false
                       },
                       tooltip: {
                            shared: true
                       }
                   }) %>
</div>

app/views/transactions/_charts.html.erb
<% colors = nil if local_assigns[:colors].nil? %>
<% pie_colors = nil if local_assigns[:pie_colors].nil? %>
<% color_by_point = false if local_assigns[:color_by_point].nil? %>
<% show_column = true if local_assigns[:show_column].nil? %>
<% show_pie = true if local_assigns[:show_pie].nil? %>
<% show_line = true if local_assigns[:show_line].nil? %>
<% show_area = false if local_assigns[:show_area].nil? %>
<% stacked = nil if local_assigns[:stacked].nil? %>

<div class="move-down">
    <h3 class="center"><%= title %></h3>
    <div class="center chart-radio-buttons">
        <div class="btn-group btn-group-toggle" data-toggle="buttons">
            <% if show_column %>
                <label class="btn btn-light active">
                    <input type="radio"
                           name="<%= name %>"
                           id="<%= name %>-column-chart-toggle"
                           autocomplete="off" checked>
                    Column
                </label>
            <% end %>

            <% if show_pie %>
                <label class="btn btn-light">
                    <input type="radio"
                           name="<%= name %>"
                           id="<%= name %>-pie-chart-toggle"
                           autocomplete="off">
                    Pie
                </label>
            <% end %>

            <% if show_line %>
                <label class="btn btn-light">
                    <input type="radio"
                           name="<%= name %>"
                           id="<%= name %>-line-chart-toggle"
                           autocomplete="off">
                    Line
                </label>
            <% end %>

            <% if show_area %>
                <label class="btn btn-light">
                    <input type="radio"
                           name="<%= name %>"
                           id="<%= name %>-area-chart-toggle"
                           autocomplete="off">
                    Area
                </label>

                <label class="btn btn-light">
                    <input type="radio"
                           name="<%= name %>"
                           id="<%= name %>-percentarea-chart-toggle"
                           autocomplete="off">
                    Percent Area
                </label>
            <% end %>
        </div>
    </div>

    <% if show_column %>
        <%= render("transactions/column_chart",
                   chart_data: chart_data,
                   title: title,
                   name: name,
                   stacked: stacked,
                   colors: colors,
                   color_by_point: color_by_point) %>
    <% end %>

    <% if show_pie %>
        <%= render("transactions/pie_chart",
                   chart_data: chart_data,
                   title: title,
                   name: name,
                   pie_colors: pie_colors) %>
    <% end %>

    <% if show_line %>
        <%= render("transactions/line_chart",
                   chart_data: chart_data,
                   title: title,
                   name: name,
                   colors: colors) %>
    <% end %>

    <% if show_area%>
        <%= render("transactions/area_chart",
                   chart_data: chart_data,
                   title: title,
                   name: name,
                   colors: colors,
                   stacked: stacked) %>
        <%= render("transactions/percent_area_chart",
                   chart_data: chart_data,
                   title: title,
                   name: name,
                   colors: colors) %>
    <% end %>
</div>

app/views/transactions/_column_chart.html.erb
<div id="<%= name %>-column">
    <%= column_chart(chart_data,
                     adapter: "highcharts",
                     prefix: "$",
                     stacked: stacked,
                     colors: colors,
                     thousands: ",",
                     title: title,
                     label: "Amount",
                     download: {background: "#FFFFFF",
                                filename: name},
                     library: {
                        plotOptions: {
                            column: {
                                animation: false,
                                colorByPoint: color_by_point,
                                dataLabels: {
                                    enabled: true,
                                    format: "${y:,.2f}"
                                }
                            }
                        }
                     }) %>
</div>

app/views/transactions/_grouped_pie_charts.html.erb
<h3 class="center move-down"><%= title %></h3>
<div class="center chart-radio-buttons">
    <div class="btn-group btn-group-toggle" data-toggle="buttons">
        <% chart_data.each_with_index do |(year, info), index| %>
            <% if index == 0 %>
                <label class="btn btn-light active">
                    <input type="radio"
                           name="<%= name %>-category-group-<%= year %>"
                           id="<%= name %>-category-group-<%= year %>-toggle"
                           autocomplete="off" checked>
                    <%= year %>
                </label>
            <% else %>
                <label class="btn btn-light">
                    <input type="radio"
                           name="<%= name %>-category-group-<%= year %>"
                           id="<%= name %>-category-group-<%= year %>-toggle"
                           autocomplete="off">
                    <%= year %>
                </label>
            <% end %>
        <% end %>
    </div>
</div>

<% chart_data.each_with_index do |(year, info), index| %>
    <%= render("transactions/pie_chart",
               chart_data: info,
               title: "Revenue by Category for #{year}",
               name: "#{name}-category-group-#{year}",
               pie_colors: nil,
               hidden: index == 0 ? "" : nil) %>
<% end %>

app/views/transactions/_line_chart.html.erb
<div id="<%= name %>-line" class="hidden">
    <%= line_chart(chart_data,
                   adapter: "highcharts",
                   prefix: "$",
                   colors: colors,
                   thousands: ",",
                   title: title,
                   label: "Amount",
                   curve: false,
                   download: {background: "#FFFFFF",
                              filename: name},
                   library: {
                    plotOptions: {
                        animation: false,
                        line: {
                            dataLabels: {
                                enabled: true,
                                format: "${y:,.2f}",
                            }
                        }
                    },
                    tooltip: {
                        shared: true
                    }
                   }) %>
</div>

app/views/transactions/_percent_area_chart.html.erb
<div id="<%= name %>-percentarea" class="hidden">
    <%= area_chart(chart_data,
                   adapter: "highcharts",
                   colors: colors,
                   thousands: ",",
                   title: title,
                   ytitle: "Percentage",
                   curve: false,
                   download: {background: "#FFFFFF",
                              filename: name},
                   library: {
                       plotOptions: {
                            animation: false,
                            area: {
                                stacking: "percent"
                            }
                       },
                       tooltip: {
                            shared: true
                       }
                   }) %>
</div>

app/views/transactions/_pie_chart.html.erb
<% hidden = "hidden" if local_assigns[:hidden].nil? %>

<div id="<%= name %>-pie" class="<%= hidden %>">
    <%= pie_chart(chart_data,
                  adapter: "highcharts",
                  prefix: "$",
                  colors: pie_colors,
                  thousands: ",",
                  title: title,
                  label: "Amount",
                  download: {background: "#FFFFFF",
                             filename: name},
                  library: {
                    plotOptions: {
                        pie: {
                            animation: false,
                            dataLabels: {
                                enabled: true,
                                format: "{point.name}: ${y:,.2f} ({percentage:.0f}%)"
                            }
                        }
                    },
                  }) %>
</div>

app/views/transactions/_summary.html.erb
<div class="col-md-4 col-xs-10">
    <div class="transaction-summary">
        <h3 class="center"><%= name %></h3>
        <ul>
            <li>
                Transactions:
                <span class="right">
                    <%= transactions.count %>
                </span>
            </li>
            <li>
                Net:
                <span class="right <%= net_color(transactions) %>">
                    <%= number_to_currency(calc_net(transactions)) %>
                </span>
            </li>
            <li>
                Revenue transactions:
                <span class="right green">
                    <%= revenue_count(transactions) %>
                </span>
            </li>
            <li>
                Revenue:
                <span class="right green">
                    <%= number_to_currency(calc_revenue(transactions)) %>
                </span>
            </li>
            <li>
                Spending transactions:
                <span class="right red">
                    <%= spending_count(transactions) %>
                </span>
            </li>
            <li>
                Spending:
                <span class="right red">
                    <%= number_to_currency(calc_spending(transactions)) %>
                </span>
            </li>
        </ul>
    </div>
</div>

app/views/transactions/comparison_charts.html.erb
<% provide(:title, "Comparison") %>

<div class="page-header">
    <h1>
        Comparison
        /
        <%= link_to("Revenue", charts_revenue_path) %>
        /
        <%= link_to("Spending", charts_spending_path) %>
    </h1>
</div>

<%= render("transactions/charts",
           chart_data: @comparison_by_totals,
           title: "Comparison by Totals",
           name: "comparison-by-totals",
           color_by_point: true,
           colors: ["#90ED7D", "#d15151"],
           pie_colors: ["#90ED7D", "#d15151"],
           show_pie: true,
           show_line: false) %>
<%= render("transactions/charts",
           chart_data: @comparison_by_year,
           title: "Comparison by Year",
           name: "comparison-by-year",
           colors: ["#90ED7D", "#d15151"],
           show_pie: false,
           show_area: true) %>
<%= render("transactions/charts",
           chart_data: @comparison_by_year_negated,
           title: "Comparison by Year",
           name: "comparison-by-year-negated",
           colors: ["#90ED7D", "#d15151"],
           stacked: true,
           show_pie: false) %>

app/views/transactions/home.html.erb
<% provide(:title, "Transactions") %>

<%= render("shared/manage_header") %>

<div class="row justify-content-around">
    <%= render("transactions/summary",
               name: "Student Org",
               transactions: @studentorg) %>
    <%= render("transactions/summary",
               name: "Allocations",
               transactions: @allocations) %>
    <%= render("transactions/summary",
               name: "Donations",
               transactions: @donations) %>
</div>

<div class="row justify-content-around move-down">
    <div class="col-xs-12 col-sm-6 move-down">
        <%= link_to(transactions_update_path,
                    class: "btn btn-primary btn-full") do %>
            <%= fa_icon("money") %> Update Transactions
        <% end %>
    </div>
    <div class="col-xs-12 col-sm-6 move-down">
        <%= link_to(charts_comparison_path,
                    class: "btn btn-primary btn-full") do %>
            <%= fa_icon("area-chart") %> Charts
        <% end %>
    </div>
</div>

app/views/transactions/revenue_charts.html.erb
<% provide(:title, "Revenue") %>

<div class="page-header">
    <h1>
        <%= link_to("Comparison", charts_comparison_path) %>
        /
        Revenue
        /
        <%= link_to("Spending", charts_spending_path) %>
    </h1>
</div>

<%= render("transactions/charts",
           chart_data: @revenue_by_year,
           title: "Revenue by Year",
           name: "revenue-by-year",
           colors: ["#90ED7D"]) %>
<%= render("transactions/charts",
           chart_data: @revenue_by_semester,
           title: "Revenue by Year and Semester",
           name: "revenue-by-semester",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/charts",
           chart_data: @revenue_by_category,
           title: "Revenue by Category",
           name: "revenue-by-category",
           colors: ["#90ED7D"],
           show_line: false) %>
<%= render("transactions/charts",
           chart_data: @revenue_by_category_and_year,
           title: "Revenue by Category and Year",
           name: "revenue-by-category-year",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/grouped_pie_charts",
           chart_data: @revenue_by_category_splits,
           title: "Revenue by Category and Year",
           name: "revenue-by-category-and-year") %>
<%= render("transactions/charts",
           chart_data: @allocations_by_year,
           title: "Allocations by Year",
           name: "allocations-by-year",
           colors: ["#90ED7D"]) %>
<%= render("transactions/charts",
           chart_data: @dues_by_year,
           title: "Dues by Year",
           name: "dues-by-year",
           colors: ["#90ED7D"]) %>
<%= render("transactions/charts",
           chart_data: @dues_by_semester,
           title: "Dues by Year and Semester",
           name: "dues-by-semester",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/charts",
           chart_data: @tournament_by_year,
           title: "Tournament Gross Earnings by Year",
           name: "tournament-by-year",
           colors: ["#90ED7D"]) %>
<%= render("transactions/charts",
           chart_data: @donations_by_year,
           title: "Donations by Year",
           name: "donations-by-year",
           colors: ["#90ED7D"]) %>
<%= render("transactions/charts",
           chart_data: @donations_by_semester,
           title: "Donations by Year and Semester",
           name: "donations-by-semester",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/charts",
           chart_data: @misc_by_year,
           title: "Miscellaneous Revenue by Year",
           name: "misc-by-year",
           colors: ["#90ED7D"]) %>

<div class="move-down"></div>

app/views/transactions/spending_charts.html.erb
<% provide(:title, "Spending") %>

<div class="page-header">
    <h1>
        <%= link_to("Comparison", charts_comparison_path) %>
        /
        <%= link_to("Revenue", charts_revenue_path) %>
        /
        Spending
    </h1>
</div>

<%= render("transactions/charts",
           chart_data: @spending_by_year,
           title: "Spending by Year",
           name: "spending-by-year",
           colors: ["#d15151"]) %>
<%= render("transactions/charts",
           chart_data: @spending_by_semester,
           title: "Spending by Year and Semester",
           name: "spending-by-semester",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/charts",
           chart_data: @spending_by_category,
           title: "Spending by Category",
           name: "spending-by-category",
           colors: ["#d15151"],
           show_line: false) %>
<%= render("transactions/charts",
           chart_data: @spending_by_category_and_year,
           title: "Spending by Year and Category",
           name: "spending-by-category-year",
           show_pie: false,
           show_area: true) %>
<%= render("transactions/grouped_pie_charts",
           chart_data: @spending_by_category_splits,
           title: "Spending by Category and Year",
           name: "spending-by-category-and-year") %>

app/views/transactions/update.html.erb
<% provide(:title, "Update Transactions") %>

<%= render("shared/page_header") %>

<div id="transaction-form" class="row justify-content-around">
    <div class="col-md-8 col-xs-10">
        <%= form_for(:update, url: transactions_scrape_url,
                     multipart: true) do |f| %>
            <%= f.label(:import_file, "Select the file") %>
            <%= f.file_field(:import_file, class: "form-control") %>

            <%= f.submit("Update",
                         id: "transaction-submit",
                         class: "btn btn-primary btn-full") %>
        <% end %>
    </div>
</div>

<div id="transaction-loader"
     class="row justify-content-around move-down"
     style="display:none">
    <div class="col-md-8 col-xs-10">
        <div class="center">
            <h2>
                Processing transactions...
                <br>
                You will be redirected automatically when done.
            </h2>
        </div>
        <div class="sk-folding-cube">
            <div class="sk-cube1 sk-cube"></div>
            <div class="sk-cube2 sk-cube"></div>
            <div class="sk-cube4 sk-cube"></div>
            <div class="sk-cube3 sk-cube"></div>
        </div>
    </div>
</div>